version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "5001:5000" # Expose Nginx on port 3000
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python-app

  python-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./obsidian-vault:/app/vault
      - ./html:/usr/share/nginx/html # Share output with Nginx
    ports:
      - "5002:5000" # Expose Flask API
    command: python process_markdown.py

  nodejs:
    image: node:18
    volumes:
      - ./js:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"

  ruby:
    image: ruby:3.2
    volumes:
      - ./ruby:/app
    working_dir: /app
    command: ruby app.rb
